### ISSUE TITLE
Add Firefox to innerText table

### ISSUE THREAD

**Issue by passcod** [kangax/jstests#3]
Firefox 45 (next nightly train, should be built sometime today according to the calendar) [has finally implemented innerText](https://twitter.com/MozWebCompat/status/661424557887131648). It would be pretty cool to see what differences it has with current implementations.

**Comment by kangax** [comment]
Yep, been working on it for the past couple hours :)

http://kangax.github.io/jstests/innerText/

**Comment by kangax** [comment]
Related: https://bugzilla.mozilla.org/show_bug.cgi?id=264412#c129

**Comment by passcod** [comment]
Awesome :)

**Comment by passcod** [comment]
Maybe add a note to your April 1st blog post with status of this?

**Comment by kangax** [comment]
Yep, I'm planning to add a section at the end, but probably after we figure out what's going on with FF's visibility:hidden issue
